name: cd

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    permissions:
      contents: 'read'
      id-token: 'write'
  
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm ci || npm install
      
      - name: Build
        run: npm run build
      
      - name: Run migrations
        run: npx drizzle-kit migrate

      # - name: Authenticate to GCP
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: YOUR_PROVIDER
      #     service_account: YOUR_SERVICE_ACCOUNT

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2

      # - name: Build and Push Docker Image
      #   run: |
      #     gcloud builds submit \
      #       --tag us-central1-docker.pkg.dev/test-cloud-run-491922/notely-repo/notely:latest

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy notely \
      #       --image us-central1-docker.pkg.dev/test-cloud-run-491922/notely-repo/notely:latest \
      #       --region us-central1 \
      #       --allow-unauthenticated \
      #       --project test-cloud-run-491922\
      #       --max-instances=4

      # - id: auth
      #   run: echo "Authenticated"

      # - name: Set up Cloud SDK
      #   run: echo "gcloud setup done"

      # - name: Build and Push Docker Image
      #   run: echo "gcloud builds submit --tag us-central1-docker.pkg.dev/notely/notely-ar-repo/notely:latest ."
